sudo: required

services:
  - docker

language: scala

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - sbt docker:publishLocal
script:
  - ./compose run --rm vendor_release_acc_tests
cache:
  directories:
  - "$HOME/.sbt"
  - "$HOME/.ivy2"

# blacklist
branches:
  except:
  - RELEASE
