sudo: required

services:
  - docker

language: scala

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
  - docker build -t sdkman/vendor-release:2.0.0-SNAPSHOT .
  - ./compose run --rm vendor_release_acc_tests
after_success:
  - docker push sdkman/vendor-release:2.0.0-SNAPSHOT
cache:
  directories:
  - "$HOME/.sbt"

# blacklist
branches:
  except:
  - RELEASE
#
