version: '2'

services:

  vendor-release:
    container_name: vendor-release
    image: sdkman/vendor-release:latest
    ports:
      - "9000:9000"
    depends_on:
      - mongo-init
      - wiremock

  mongo-init:
    container_name: mongo-init
    image: mongo:3.2
    depends_on:
      - mongo
    volumes:
      - $PWD/wait-for-it.sh:/wait-for-it.sh
    command: bash -c "/wait-for-it.sh -h mongo -p 27017 -t 30 -- mongo --host mongo --port 27017 --eval 'db.version()'"

  mongo:
    container_name: mongo
    image: mongo:3.2
    ports:
      - "27017:27017"

  wiremock:
    container_name: wiremock
    image: rodolpheche/wiremock:latest
    ports:
      - "8080:8080"

  vendor_release_acc_tests:
    image: nightscape/docker-sbt:latest
    working_dir: /work
    user: ${USER_ID}
    environment:
      SBT_CACHE: "/sbt"
      IVY_CACHE: "/ivy2"
    volumes:
      - ${PWD}:/work
      - ${HOME}/.sbt:/sbt
      - ${HOME}/.ivy2:/ivy2
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/bin/docker
    depends_on:
      - vendor-release
    command: ./sbtw acc:test
